services:
  - type: web
    name: study-backend
    rootDirectory: backend
    env:
      PYTHON_VERSION: 3.13.4
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
